# Global confiuration: Applied to all files

semi = false
singleQuote = false
quoteProps = "as-needed"
jsxSingleQuote = false
trailingComma = "es5"
bracketSpacing = true
objectWrap = "preserve"
bracketSameLine = false
arrowParens = "always"
proseWrap = "always"
htmlWhitespaceSensitivity = "css"
vueIndentScriptAndStyle = true
embeddedLanguageFormatting = "auto"
singleAttributePerLine = false

# Overrides used to specify format for specific files

[[overrides]]
files = "*.md"

[overrides.options]
printWidth = 80
tabWidth = 2
