# See "Configuring Rustfmt" for more information:
# https://github.com/rust-lang/rustfmt/blob/main/Configurations.md

comment_width = 80
edition = "2024"
force_explicit_abi = true
hard_tabs = false
max_width = 80
merge_derives = true
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
wrap_comments = true
